# Generated by Django 6.0.3 on 2026-04-26 00:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Valor não pode ser menor que 0.'), django.core.validators.MaxValueValidator(5, 'Valor não pode ser maior que 5.')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='games.games')),
            ],
        ),
    ]
