# Generated by Django 6.0.3 on 2026-04-09 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developers', '0001_initial'),
        ('genres', '0001_initial'),
        ('platforms', '0001_initial'),
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_game', models.CharField(max_length=200)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('developers', models.ManyToManyField(to='developers.developers')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='genres.genre')),
                ('platform', models.ManyToManyField(to='platforms.platforms')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publisher.publisher')),
            ],
        ),
    ]
