# Generated by Django 6.0.3 on 2026-04-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PC_STEAM', 'PC (Steam)'), ('XBOX_360', 'Xbox 360'), ('XBOX_ONE', 'Xbox One'), ('XBOX_SERIES', 'Xbox Series X/S'), ('PS4', 'PlayStation 4'), ('PS5', 'PlayStation 5'), ('NINT_SWITCH', 'Nintendo Switch')], max_length=50)),
            ],
        ),
    ]
