# Generated by Django 6.0.3 on 2026-04-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('USA', 'AMERICAN'), ('BRAZIL', 'BRAZILLIAN'), ('JAPAN', 'JAPANESE')], max_length=100, null=True)),
            ],
        ),
    ]
